title: Market Pulse
description: Pulse of the markets, tech, life, and everything in between.
author: Your Name Here
baseurl: "/mp"                    # leave empty for root
url: "https://soumithhh.github.io/mp"   # update after deploy
permalink: /:title/
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
paginate: 8
paginate_path: "/page/:num/"
future: true
